# Generated by Django 3.2.12 on 2022-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20220222_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='placeId',
            new_name='place_id',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
