# Generated by Django 3.2.12 on 2022-02-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер изображения'),
        ),
    ]
